package net.empire.ewmedieval.world;

import net.empire.ewmedieval.EwMedieval;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;
import net.minecraft.world.gen.feature.ConfiguredFeature;

/**
 * Registry key constants for configured features.
 * JSON files are generated by ModWorldGenProvider (run ./gradlew runDatagen).
 * Keys must match the tree names defined in ModWorldGenProvider.TREES.
 */
public class ModConfiguredFeatures {

    public static final RegistryKey<ConfiguredFeature<?, ?>> AVOCADO_TREE =
            RegistryKey.of(RegistryKeys.CONFIGURED_FEATURE,
                    new Identifier(EwMedieval.MOD_ID, "avocado_tree"));
}